<a href="https://colab.research.google.com/github/daizybhadresha/python_data_science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Creation

In [11]:
#### Creating with Numerical Ranges

import numpy as np

# NumPy array from 1 to 19 with step size 2
print(np.arange(1,20,2,dtype='int8'))

# Diff element type can be created but at the end it will be of same type
narray = np.array([1,2,3,4,'sum'])
print(narray)


[ 1  3  5  7  9 11 13 15 17 19]
['1' '2' '3' '4' 'sum']


In [5]:
import numpy as np
import sys

narray = np.array([1,2,3,4])

my_list = [1,2,3,4]

print(narray.__sizeof__())
print(my_list.__sizeof__())
print(sys.getsizeof(narray))
print(sys.getsizeof(my_list))

128
72
128
104


In [18]:
#### Initial Placeholders : Ways of creating arrays

import numpy as np

# arbitrary array of specified shape and dtype  --- new values will occur as many times we run
print(np.empty((3,4),dtype='string_'))

# Creates a new array of specified size and type, filled with 0
print(np.zeros((3,4),dtype='int8'))

# Creates a new array of specified size and type, filled with 1
print(np.ones((3,4),dtype='int8'))

# Creates a new array of given shape and type, filled with a constant value
print(np.full((2,2),5))
print(np.full((1,5),5))

# Creates a 2-D array with ones on the diagonal and zeros elsewhere  -- by default float
# 5*5
np.eye(5, dtype=int)


[[b'`' b'\x94' b'[' b'\x06']
 [b'j' b'U' b'' b'']
 [b'\x02' b'' b'' b'']]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[5 5]
 [5 5]]
[[5 5 5 5 5]]


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
#### Creating with an existing Data

import numpy as np

#python list
a=[1,2,3]

#convert to NumPy array
b=np.asarray(a)
print(b)

#python tuples
a=((1,2),(3,4))

#convery to NumPy array
b=np.asarray(a)
print(b)

#creates a NumPy ndarray from an iterable. creating arrays from list a, tuple b, range( ) and finally a string d
a=np.fromiter([1,2,3,4],dtype='int8')
b=np.fromiter((1,2,3,4),dtype='int8')
c=np.fromiter(range(1,5),dtype='int8')
d=np.fromiter('string',dtype='S50')

print("Array a is ",a)
print("Array b is ",b)
print("Array c is ",c)
print("Array d is ",d)

[1 2 3]
[[1 2]
 [3 4]]
Array a is  [1 2 3 4]
Array b is  [1 2 3 4]
Array c is  [1 2 3 4]
Array d is  [b's' b't' b'r' b'i' b'n' b'g']


In [20]:
#### Creating with Numerical Ranges

import numpy as np             

# NumPy array from 1 to 19 with step size 2
print(np.arange(5))
print(np.arange(1,20,2,dtype='int8'))          # numpy.arange(start, stop, step, dtype)


# Returns an array within a range according to the number of values we want within that range. 

# NumPy array from 1 to 20 with 100 numbers in between
print(np.linspace(1,20,100))                   # numpy.linspace(start, stop, num, endpoint, retstep, dtype)


# returns an array containing numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10. 

# NumPy array from 10^0 to 10^2 with 100 numbers in log scale - There are 100 values in the range of [10^0, 10^2]. 
print(np.logspace(0,2,100))                    # numpy.logspace(start, stop, num, endpoint, base, dtype)



[0 1 2 3 4]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1.          1.19191919  1.38383838  1.57575758  1.76767677  1.95959596
  2.15151515  2.34343434  2.53535354  2.72727273  2.91919192  3.11111111
  3.3030303   3.49494949  3.68686869  3.87878788  4.07070707  4.26262626
  4.45454545  4.64646465  4.83838384  5.03030303  5.22222222  5.41414141
  5.60606061  5.7979798   5.98989899  6.18181818  6.37373737  6.56565657
  6.75757576  6.94949495  7.14141414  7.33333333  7.52525253  7.71717172
  7.90909091  8.1010101   8.29292929  8.48484848  8.67676768  8.86868687
  9.06060606  9.25252525  9.44444444  9.63636364  9.82828283 10.02020202
 10.21212121 10.4040404  10.5959596  10.78787879 10.97979798 11.17171717
 11.36363636 11.55555556 11.74747475 11.93939394 12.13131313 12.32323232
 12.51515152 12.70707071 12.8989899  13.09090909 13.28282828 13.47474747
 13.66666667 13.85858586 14.05050505 14.24242424 14.43434343 14.62626263
 14.81818182 15.01010101 15.2020202  15.39393939 15.58585859 15.77777778
 15.969

### Methods & Attributes

In [10]:
##### Numpy Exploration Methods

import numpy as np

# initialize NumPy array
array = np.arange(1, 11)
print(array)

# check dimensions : Total no of demension
dim = array.ndim
print("Dimension : ", dim)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension :  1


In [12]:
array = np.arange(1, 11)
# reshaped array
reshaped = array.reshape(5,2)
print("Reshaped array\n",reshaped)

# check dimensions
sha = reshaped.shape
print("Dimension : ", reshaped.ndim)
print("Shape : ", sha)

# Total elements
print("Length:",len(array))
print("Size:",array.size)

# get the number of bytes in each element of the array
print("Itemsize:",array.itemsize)

Reshaped array
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Dimension :  2
Shape :  (5, 2)
Length: 10
Size: 10
Itemsize: 8


In [13]:
# can reshape as well as resize(can add new elements i.e. 0) array
a = np.array([[0, 1], [2, 3]])
a.resize((5,3))
print("Resized array\n",a)

Resized array
 [[0 1 2]
 [3 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#### Find a 3x3 Non Singular Matrix

I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Mathematical Operations

In [ ]:
#### Vectorization : Operations on entire array rather than single element
# Add, Sub, Mult, Div, Sqrt, Log
# Agg Function : Min, Max, Mean, Mode, Median, std, corr coeff, cum sum(cumulative sum of elems)
# Array comp : np.array_equal(a,b)
# Axes notation : By changing axis you can compute across dimensions, whereas not specifying axis will result in computation over the entire array.

# Boolean indexing
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[a > 2])
print(a[a - 2])

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])

print(a+b)
print(np.add(a,b))

print(a-b)
print(np.subtract(a,b))

print(a*b)
print(np.multiply(a,b))

print(a/b)
print(np.divide(a,b))

print(np.sqrt(a))

print(np.log(a))

print(np.array_equal(a,b))

# Axes notation : using agg function
print(a.min(axis=0))                  # axis = 0 -> row wise 

In [21]:
#  Agg Function : Min, Max, Mean, Mode, Median, std, corr coeff, cum sum(cumulative sum of elems)
import numpy as np
a = np.array([1,2,3,4,5,6,7])

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]])
b = a.sum(axis=1)
print (b)

a = np.array([[0, 1, 0], [1, 0, 1]])
a += 3
b = a + 3
print (a[1,2] + b[1,2])

a = np.zeros(6)
b = np.arange(0,10,2)
print(a,b)
#c = a + b
#print (c[4])

a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)
d = a + b + c
print(d[1,2])

[ 3 12]
11
[0. 0. 0. 0. 0. 0.] [0 2 4 6 8]
5


In [ ]:
print(np.random.seed(22))
z = np.random.random((5,5))
print(z)
print(type(z))
zmax = z.min()
zmin = z.max()
print(zmax,zmin)

None
[[0.20846054 0.48168106 0.42053804 0.859182   0.17116155]
 [0.33886396 0.27053283 0.69104135 0.22040452 0.81195092]
 [0.01052687 0.5612037  0.81372619 0.7451003  0.18911136]
 [0.00614087 0.77204387 0.95783217 0.70193788 0.29757827]
 [0.76799274 0.68821832 0.38718348 0.61520583 0.42755524]]
<class 'numpy.ndarray'>
0.006140866346098228 0.9578321680932752


Similarities between NumPy arrays and lists
NumPy arrays and Python lists are in fact very similar to one another in many aspects. 
Numpy arrays with more than a single dimension can be thought of as nested lists. 

Other common similarities are:

1.   Both are used for storing data
2.   Both are mutable
1.   Both can be indexed and iterated through
2.   Both can be sliced

Advantages of using NumPy


Numpy data structures perform better in:



*   Size: Numpy data structures take up less space
*   Performance: They have a need for speed and are faster than lists
*   Functionality: NumPy have optimized functions such as linear algebra operations built in.









### Broadcasting

In [9]:
import numpy as np

# Either r=r  or  c=c  or  r*c=c*r
print(np.arange(3) + 5)                                 #  1*3 + 1*1 
print(np.ones((4,3)) + np.arange(3))                    #  4*3 + 1*3
#print(np.ones((4,3)) + np.arange(4))                   #  4*3 + 1*4  # error
print(np.ones((4,3)) + np.a range(4).reshape(4,1))       #  4*3 + 4*1
print(np.ones((4,3)) + np.arange(4).reshape(4,1))       #  4*3 + 4*1
print(np.arange(4).reshape(4,1) + np.ones((4)))         #  4*1 + 1*4

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


### dir

In [ ]:
import numpy as np
narray = np.array([1,2,3,4])
dir(narray)

### Indexing & Slicing

In [ ]:
#### Indexing & Slicing

import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])


print(a[2][1])   # 3rd elem 2nd row
print(a[:2,:2])  # 1st 2 rows & 1st 2 cols
print(a[2,:])    # all elements of the third row (0 1 2)

# integer array indexing
a=np.array([[1,2],[3,4],[5,6]])

print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))

print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

a = np.array([[4,7,1],[2,5,7],[7,1,1]])

# Boolean indexing

mask = a ? 3     # Boolean condition for values greater than 3
print(mask)
print(a[mask])   # Masking for the above boolean condition in the array  -- return only true elems

8
[[1 2]
 [4 5]]
[7 8 9]
[1 4 5]
[1 4 5]
[2 2]
[2 2]
[[False False False]
 [False False False]
 [False False False]]
[]


## Implementations

In [17]:
#### Find roots of quadratic equation

# import packages
import numpy as np

# Code starts here

# co-efficients of x
coeff  = np.array([1, -4, 4])

# roots of equation
roots = np.roots(coeff)

# display roots
print(roots)

# Code ends here

[2. 2.]


### Quadratic Equation

![alt text](https://storage.googleapis.com/ga-commit-live-prod-live-data/account/b92/11111111-1111-1111-1111-000000000000/b-235/99134bce-ccc8-49eb-9ff9-cb3c765dc1f9/file.jpg)

### Centrigrade to Fahrenheit

In [ ]:
#### Centrigrade to Fahrenheit

# Code starts here
import numpy as np
# centigrade temperatures
centigrade_temps = np.array([0, 10, 25, 32, 80, 99.99])

# function for conversion
def convert(celsius):
   return (celsius * 1.8) + 32
     
# display fahrehheit temperatures
print(convert(centigrade_temps))

# Code ends here

[ 32.     50.     77.     89.6   176.    211.982]
